### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by oganator** [nswekosk/fred_go_toolkit#1]
I have an API key from FRED which works, but where do i put it within the code so that i can run package tests?

**Comment by nswekosk** [comment]
@oganator You may set the API Key as an environment variable or leverage the helper methods on the client. The following test provides examples:
* https://github.com/nswekosk/fred_go_toolkit/blob/master/fred_toolkit_v1_test.go

Anything else I can help you with?

**Comment by nswekosk** [comment]
Closing issue due to lack of a response.
